language: python
python:
  - 2.7
  - 3.6
cache:
  pip: true
  directories:
  - eggs
matrix:
  fast_finish: true
before_install:
  - pip install zc.buildout
install:
  - buildout -N -t 3 annotate
  - buildout -N -t 3
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
